/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "knative.dev/eventing-ceph/pkg/apis/sources/v1alpha1"
)

// CephSourceLister helps list CephSources.
// All objects returned here must be treated as read-only.
type CephSourceLister interface {
	// List lists all CephSources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CephSource, err error)
	// CephSources returns an object that can list and get CephSources.
	CephSources(namespace string) CephSourceNamespaceLister
	CephSourceListerExpansion
}

// cephSourceLister implements the CephSourceLister interface.
type cephSourceLister struct {
	listers.ResourceIndexer[*v1alpha1.CephSource]
}

// NewCephSourceLister returns a new CephSourceLister.
func NewCephSourceLister(indexer cache.Indexer) CephSourceLister {
	return &cephSourceLister{listers.New[*v1alpha1.CephSource](indexer, v1alpha1.Resource("cephsource"))}
}

// CephSources returns an object that can list and get CephSources.
func (s *cephSourceLister) CephSources(namespace string) CephSourceNamespaceLister {
	return cephSourceNamespaceLister{listers.NewNamespaced[*v1alpha1.CephSource](s.ResourceIndexer, namespace)}
}

// CephSourceNamespaceLister helps list and get CephSources.
// All objects returned here must be treated as read-only.
type CephSourceNamespaceLister interface {
	// List lists all CephSources in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CephSource, err error)
	// Get retrieves the CephSource from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.CephSource, error)
	CephSourceNamespaceListerExpansion
}

// cephSourceNamespaceLister implements the CephSourceNamespaceLister
// interface.
type cephSourceNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.CephSource]
}
