apiVersion: v1
kind: Service
metadata:
  name: ceph-bucket-notifications
spec:
  selector:
    knative-eventing-source-name: ceph-source1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
